import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "./sidenav";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="flex h-screen flex-col  md:flex-row md:overflow-hidden">
                <SideNav />
                {children}
            </body>
        </html>
    );
}
